baseURL = "https://github.com/agsayyed/mcq"
title = "mcq"
description = "Moudle is used with hugo shortcodes to display multipe choice questin format, reading from a hugo site's data directory in an accordion. question answers are kept in yml format"

[module]
hugoVersion.min = "0.110.0"

[[module.imports]]
path = "github.com/hugomods/bootstrap"

[[module.imports]]
path = "github.com/hugomods/icons"

[[module.imports]]
path = "github.com/twbs/icons"

[params.hb]
bootstrap.enable_library = true

