[module.hugoVersion]
min = "0.110.0"

[[module.imports]]
path = "github.com/hugomods/bootstrap"

[[module.imports]]
path = "github.com/hugomods/icons"

[[module.imports]]
path = "github.com/twbs/icons"